/**
 * @file lib/migrations/baseRaidLabelBackfill.ts
 * @created 2026-09-13
 * @overview FID-20260912-093b — backfill the BASE_RAID label onto historical
 * rows written before the FID-093 relabel.
 *
 * Before FID-093, /api/combat/attack resolved base raids as
 * BattleType.Factory, so battle_logs rows AND the system battle-report
 * messages (whose headline text embeds the type) say FACTORY for what were
 * really raids on hostile bases. Meanwhile /api/factory/attack — the real
 * factory capture path — never writes battle_logs rows at all, so EVERY
 * FACTORY battle_logs row whose defender is a bot is a mislabeled base raid.
 *
 * Heal rule (conservative, evidence-based):
 *   battle_logs:  battle_type='FACTORY' AND the defender classifies as a bot
 *                 base → 'BASE_RAID'. Two classifiers, because destroyed
 *                 beer bases have their players row DELETED (join null):
 *                 1. players.is_bot = 1 (live bots), OR
 *                 2. the bot-name shape — compact 'b<tier><ts12>' or a
 *                    themed beer-base name (generated by generateBeerBaseName).
 *                 Real factory captures never write battle_logs rows, so a
 *                 FACTORY row with a bot defender is unambiguous.
 *   messages:     system battle_result whose content headline says
 *                 '— FACTORY at' AND whose related battle id now maps to a
 *                 BASE_RAID row → headline rewritten to 'BASE RAID'.
 * Drift-guarded: free when no mislabeled rows remain.
 */
import { sql, eq } from 'drizzle-orm';
import { db } from '../db';
import { migrations } from '../db/schema';

const MIGRATION_ID = '0033_base_raid_label_backfill';

export async function runBaseRaidLabelBackfillMigration(): Promise<{
  success: boolean;
  message: string;
  logsRewritten?: number;
  messagesRewritten?: number;
  previewsRewritten?: number;
  alreadyApplied?: boolean;
}> {
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS "migrations" (
      "id" varchar(100) PRIMARY KEY,
      "applied_at" timestamp NOT NULL,
      "details" jsonb
    )
  `);

  const existing = await db.select().from(migrations).where(eq(migrations.id, MIGRATION_ID));
  const markerExists = existing.length > 0;

  // 1) battle_logs: FACTORY rows with a bot-base defender → BASE_RAID.
  //    Classifier A: live join on players.is_bot. Classifier B: the bot-name
  //    shape (compact beer id or themed name) — destroyed bases have no row
  //    to join, but the name is still the fingerprint of the raid era.
  const rewritten = await db.execute(sql`
    UPDATE battle_logs b
    SET battle_type = 'BASE_RAID'
    WHERE b.battle_type = 'FACTORY'
      AND (
        EXISTS (SELECT 1 FROM players p WHERE p.username = b.defender_username AND p.is_bot = 1)
        OR b.defender_username ~ '^b[WMSEUL][0-9]{12}$'
        OR b.defender_username IN (
          'Silent_Citadel','Sable_Fortress','Forsaken_Warrens','Shattered_Den',
          'Iron_Alehall','Amber_Vault','Copper_Keg','Bronze_Brewery'
        )
      )
  `);
  const logsRewritten = rewritten.rowCount ?? 0;

  // 2) battle-report messages: rewrite the FACTORY headline to BASE RAID for
  //    reports whose battle id was just relabeled (or whose defender is a bot).
  //    The headline is line 1 of the stored content; the card/feed parse it.
  const messagesRewritten = await db.execute(sql`
    UPDATE messages m
    SET content = regexp_replace(m.content, '— FACTORY at', '— BASE RAID at')
    FROM battle_logs b
    WHERE m.metadata_related_entity_id = left(b.battle_id, 50)
      AND m.metadata_system_type = 'battle_result'
      AND b.battle_type = 'BASE_RAID'
      AND m.content LIKE '%— FACTORY at%'
  `);
  const messagesCount = messagesRewritten.rowCount ?? 0;

  // 3) conversation previews: conversations.last_message_content caches the
  //    newest message text for the inbox list — it kept saying FACTORY even
  //    after the message bodies were fixed. Only base raids ever wrote
  //    battle-report messages (real factory captures never persist logs), so
  //    every cached '— FACTORY at' preview is a raid mislabel.
  const previewsRewritten = await db.execute(sql`
    UPDATE conversations
    SET last_message_content = regexp_replace(last_message_content, '— FACTORY at', '— BASE RAID at')
    WHERE last_message_content LIKE '%⚔️ BATTLE REPORT — FACTORY at%'
  `);
  const previewCount = previewsRewritten.rowCount ?? 0;

  if (!markerExists) {
    await db.insert(migrations).values({
      id: MIGRATION_ID,
      appliedAt: new Date(),
      details: { logsRewritten, messagesRewritten: messagesCount, previewsRewritten: previewCount },
    });
  }

  return {
    success: true,
    message: `Base raid label backfill: ${logsRewritten} battle log(s), ${messagesCount} report message(s), ${previewCount} inbox preview(s) relabeled`,
    logsRewritten,
    messagesRewritten: messagesCount,
    previewsRewritten: previewCount,
    alreadyApplied: markerExists,
  };
}
