import { pgTable, varchar, integer, smallint, timestamp, jsonb, index } from 'drizzle-orm/pg-core';
import type { Unit, CombatRound } from '@/types/game.types';

export const battleLogs = pgTable('battle_logs', {
	battleId: varchar('battle_id', { length: 50 }).primaryKey(),
	battleType: varchar('battle_type', { length: 20 }).notNull(),
	timestamp: timestamp('timestamp').notNull(),
	attackerUsername: varchar('attacker_username', { length: 20 }).notNull(),
	attackerUnits: jsonb('attacker_units').notNull().$type<Unit[]>(),
	attackerTotalSTR: integer('attacker_total_str').notNull(),
	attackerTotalDEF: integer('attacker_total_def').notNull(),
	attackerInitialHP: integer('attacker_initial_hp').notNull(),
	attackerFinalHP: integer('attacker_final_hp').notNull(),
	attackerUnitsLost: integer('attacker_units_lost').notNull(),
	attackerUnitsCaptured: integer('attacker_units_captured').notNull(),
	attackerStartingHP: integer('attacker_starting_hp').notNull(),
	attackerEndingHP: integer('attacker_ending_hp').notNull(),
	attackerDamageDealt: integer('attacker_damage_dealt').notNull(),
	attackerXpEarned: integer('attacker_xp_earned').notNull(),
	defenderUsername: varchar('defender_username', { length: 20 }).notNull(),
	defenderUnits: jsonb('defender_units').notNull().$type<Unit[]>(),
	defenderTotalSTR: integer('defender_total_str').notNull(),
	defenderTotalDEF: integer('defender_total_def').notNull(),
	defenderInitialHP: integer('defender_initial_hp').notNull(),
	defenderFinalHP: integer('defender_final_hp').notNull(),
	defenderUnitsLost: integer('defender_units_lost').notNull(),
	defenderUnitsCaptured: integer('defender_units_captured').notNull(),
	defenderStartingHP: integer('defender_starting_hp').notNull(),
	defenderEndingHP: integer('defender_ending_hp').notNull(),
	defenderDamageDealt: integer('defender_damage_dealt').notNull(),
	defenderXpEarned: integer('defender_xp_earned').notNull(),
	outcome: varchar('outcome', { length: 20 }).notNull(),
	rounds: jsonb('rounds').notNull().$type<CombatRound[]>(),
	totalRounds: integer('total_rounds').notNull(),
	unitsCapturedAttackerCaptured: jsonb('units_captured_attacker_captured').$type<Unit[]>(),
	unitsCapturedDefenderCaptured: jsonb('units_captured_defender_captured').$type<Unit[]>(),
	attackerXP: integer('attacker_xp').notNull(),
	defenderXP: integer('defender_xp').notNull(),
	resourcesStolenResourceType: varchar('resources_stolen_resource_type', { length: 20 }),
	resourcesStolenAmount: integer('resources_stolen_amount'),
	locationX: smallint('location_x'),
	locationY: smallint('location_y'),
}, (table) => [
	index('battle_logs_attacker_timestamp_idx').on(table.attackerUsername, table.timestamp),
	index('battle_logs_defender_timestamp_idx').on(table.defenderUsername, table.timestamp),
	index('battle_logs_timestamp_idx').on(table.timestamp),
]);
