import { pgTable, varchar, integer, smallint, timestamp, numeric, jsonb, text, index, uniqueIndex } from 'drizzle-orm/pg-core';
import type { InventoryItem, TutorialInventoryItem, ShrineBoost, PlayerUnit, BalanceEffects, BotConfig, ResearchPointHistory } from '@/types/game.types';
import type { PlayerBounties } from '@/lib/bountyBoardService';
import type { Specialization } from '@/lib/specializationService';

export const players = pgTable('players', {
	username: varchar('username', { length: 20 }).primaryKey(),
	mongoId: varchar('_id', { length: 24 }),
	email: varchar('email', { length: 255 }).notNull(),
	password: varchar('password', { length: 255 }).notNull(),
	baseX: integer('base_x').notNull(),
	baseY: integer('base_y').notNull(),
	currentPositionX: integer('current_position_x').notNull(),
	currentPositionY: integer('current_position_y').notNull(),
	resourcesMetal: integer('resources_metal', ).notNull().default(0),
	resourcesEnergy: integer('resources_energy', ).notNull().default(0),
	bankMetal: integer('bank_metal', ).notNull().default(0),
	bankEnergy: integer('bank_energy', ).notNull().default(0),
	bankLastDeposit: timestamp('bank_last_deposit'),
	rank: integer('rank').default(1),
	inventoryItems: jsonb('inventory_items').notNull().$type<Array<InventoryItem | TutorialInventoryItem>>().default([]),
	inventoryCapacity: integer('inventory_capacity').notNull().default(2000),
	inventoryMetalDiggerCount: integer('inventory_metal_digger_count').notNull().default(0),
	inventoryEnergyDiggerCount: integer('inventory_energy_digger_count').notNull().default(0),
	gatheringBonusMetalBonus: numeric('gathering_bonus_metal_bonus', { precision: 5, scale: 2 }).notNull().default('0'),
	gatheringBonusEnergyBonus: numeric('gathering_bonus_energy_bonus', { precision: 5, scale: 2 }).notNull().default('0'),
	activeBoostsGatheringBoost: numeric('active_boosts_gathering_boost', { precision: 5, scale: 2 }),
	activeBoostsExpiresAt: timestamp('active_boosts_expires_at'),
	shrineBoosts: jsonb('shrine_boosts').notNull().$type<ShrineBoost[]>().default([]),
	units: jsonb('units').notNull().$type<PlayerUnit[]>().default([]),
	totalStrength: integer('total_strength').notNull().default(0),
	totalDefense: integer('total_defense').notNull().default(0),
	balanceEffects: jsonb('balance_effects').$type<BalanceEffects | null>(),
	xp: integer('xp').notNull().default(0),
	level: integer('level').notNull().default(1),
	researchPoints: integer('research_points').notNull().default(0),
	unlockedTiers: jsonb('unlocked_tiers').notNull().$type<number[]>().default([]),
	unlockedTechs: jsonb('unlocked_techs').$type<string[]>(),
	concentrationZones: jsonb('concentration_zones').$type<Array<{ centerX: number; centerY: number; size: number; name?: string }>>(),
	lastBotSummon: timestamp('last_bot_summon'),
	fastTravelWaypoints: jsonb('fast_travel_waypoints').$type<Array<{ name: string; x: number; y: number; setAt: Date }>>(),
	lastFastTravel: timestamp('last_fast_travel'),
	dailyBounties: jsonb('daily_bounties').$type<PlayerBounties | null>(),
	specialization: jsonb('specialization').$type<Specialization | null>(),
	discoveries: jsonb('discoveries').$type<Record<string, unknown>[]>(),
	achievements: jsonb('achievements').$type<Record<string, unknown>[]>(),
	stats: jsonb('stats').$type<Record<string, number>>(),
	factoryCount: integer('factory_count').default(0),
	lastXPAward: timestamp('last_xp_award'),
	lastLevelUp: timestamp('last_level_up'),
	rpHistory: jsonb('rp_history').$type<ResearchPointHistory[]>(),
	baseGreeting: varchar('base_greeting', { length: 500 }),
	battleStats: jsonb('battle_stats').$type<Record<string, unknown>>(),
	isBot: smallint('is_bot').default(0),
	isSpecialBase: smallint('is_special_base').default(0),
	botConfig: jsonb('bot_config').$type<BotConfig>(),
	clanId: varchar('clan_id', { length: 24 }),
	clanName: varchar('clan_name', { length: 30 }),
	clanRole: varchar('clan_role', { length: 20 }),
	clanLevel: integer('clan_level'),
	isAdmin: smallint('is_admin').default(0),
	vip: smallint('vip').default(0),
	vipExpiration: timestamp('vip_expiration'),
	vipTier: varchar('vip_tier', { length: 20 }),
	stripeCustomerId: varchar('stripe_customer_id', { length: 255 }),
	stripeSubscriptionId: varchar('stripe_subscription_id', { length: 255 }),
	vipLastUpdated: timestamp('vip_last_updated'),
	lastLoginDate: timestamp('last_login_date'),
	loginStreak: integer('login_streak').default(0),
	lastStreakReward: timestamp('last_streak_reward'),
	currentHP: integer('current_hp').default(1000),
	maxHP: integer('max_hp').default(1000),
	lastFlagAttack: timestamp('last_flag_attack'),
	referralCode: varchar('referral_code', { length: 20 }),
	referralLink: varchar('referral_link', { length: 255 }),
	referredBy: varchar('referred_by', { length: 20 }),
	referredByUsername: varchar('referred_by_username', { length: 20 }),
	referralValidated: smallint('referral_validated'),
	referralValidatedAt: timestamp('referral_validated_at'),
	totalReferrals: integer('total_referrals').default(0),
	pendingReferrals: integer('pending_referrals').default(0),
	referralRewardsMetal: integer('referral_rewards_metal', ),
	referralRewardsEnergy: integer('referral_rewards_energy', ),
	referralRewardsRp: integer('referral_rewards_rp'),
	referralRewardsXp: integer('referral_rewards_xp'),
	referralRewardsVipDays: integer('referral_rewards_vip_days'),
	referralTitles: jsonb('referral_titles').$type<string[]>(),
	referralBadges: jsonb('referral_badges').$type<string[]>(),
	referralMultiplier: numeric('referral_multiplier', { precision: 3, scale: 1 }).default('1.0'),
	lastReferralValidated: timestamp('last_referral_validated'),
	referralMilestonesReached: jsonb('referral_milestones_reached').$type<number[]>(),
	signupIP: varchar('signup_ip', { length: 45 }),
	protectionUntil: timestamp('protection_until'),
	createdAt: timestamp('created_at').defaultNow(),
	// Account-ban gate columns (written by admin ban flow, read at login). smallint 0/1.
	banned: smallint('banned').default(0),
	banReason: text('ban_reason'),
	bannedAt: timestamp('banned_at'),
	bannedBy: varchar('banned_by', { length: 20 }),
	banExpiresAt: timestamp('ban_expires_at'),
}, (table) => [
	uniqueIndex('email_unique').on(table.email),
	index('clan_idx').on(table.clanId, table.clanRole),
	index('level_idx').on(table.level),
]);
