import { pgTable, varchar, integer, smallint, timestamp, text, index } from 'drizzle-orm/pg-core';

export const referrals = pgTable('referrals', {
	id: varchar('id', { length: 24 }).primaryKey(),
	referrerCode: varchar('referrer_code', { length: 20 }).notNull(),
	referrerUsername: varchar('referrer_username', { length: 20 }).notNull(),
	referrerPlayerId: varchar('referrer_player_id', { length: 24 }).notNull(),
	newPlayerUsername: varchar('new_player_username', { length: 20 }).notNull(),
	newPlayerEmail: varchar('new_player_email', { length: 255 }).notNull(),
	newPlayerIP: varchar('new_player_ip', { length: 45 }).notNull(),
	signupDate: timestamp('signup_date').notNull(),
	validationDate: timestamp('validation_date'),
	validated: smallint('validated').notNull().default(0),
	loginCount: integer('login_count').notNull().default(0),
	lastLogin: timestamp('last_login'),
	daysActive: integer('days_active').notNull().default(0),
	rewardsClaimed: smallint('rewards_claimed').notNull().default(0),
	rewardsDataMetal: integer('rewards_data_metal').notNull().default(0),
	rewardsDataEnergy: integer('rewards_data_energy').notNull().default(0),
	rewardsDataRp: integer('rewards_data_rp').notNull().default(0),
	rewardsDataXp: integer('rewards_data_xp').notNull().default(0),
	rewardsDataVipDays: integer('rewards_data_vip_days').notNull().default(0),
	rewardsDataSpecialReward: varchar('rewards_data_special_reward', { length: 100 }),
	rewardsDataMilestone: integer('rewards_data_milestone'),
	welcomePackageGiven: smallint('welcome_package_given').notNull().default(0),
	flaggedForAbuse: smallint('flagged_for_abuse').notNull().default(0),
	invalidated: smallint('invalidated').notNull().default(0), // migration 0011 — admin invalidation marker
	flagReason: varchar('flag_reason', { length: 255 }),
	adminNotes: text('admin_notes'),
	createdAt: timestamp('created_at').notNull(),
	updatedAt: timestamp('updated_at').notNull(),
}, (table) => [
	index('referrals_referrer_validated_idx').on(table.referrerUsername, table.validated),
	index('referrals_new_player_username_idx').on(table.newPlayerUsername),
	index('referrals_signup_date_idx').on(table.signupDate),
	index('referrals_validated_validation_date_idx').on(table.validated, table.validationDate),
]);
