-- Migration 0010: Phantom raw-SQL tables + game_config.type uniqueness (FID-20260904-005 Phase 4)
--
-- Five tables are written by raw SQL in services but never existed in the live database
-- (every write failed; every read returned empty). Column sets are derived EXACTLY from
-- the INSERT/UPDATE/SELECT statements in the owning services:
--   clan_chat_messages   <- lib/clanChatService.ts:163,196,226,373
--   clan_activities      <- lib/clanActivityService.ts:56,121,157,185
--   clan_alliances       <- lib/clanAllianceService.ts:227,315,269
--   activity_logs        <- lib/clanActivityService.ts:73
--   beer_base_config     <- lib/beerBaseService.ts getBeerBaseConfig/updateBeerBaseConfig
-- Plus: game_config.type gains a UNIQUE constraint (the shim's race-safe upsert on
-- {type} — used by beer-base config and warfare config — requires it; mirrors the
-- drizzle index already declared in lib/db/schema/config.ts).

-- ---------------------------------------------------------------------------
-- clan_chat_messages (raw-SQL table: ids generated by the caller, 24 chars)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clan_chat_messages (
  id varchar(24) PRIMARY KEY,
  clan_id varchar(24) NOT NULL,
  type varchar(20) NOT NULL,
  player_id varchar(20),
  username varchar(20),
  role varchar(20),
  message text NOT NULL,
  timestamp timestamptz NOT NULL,
  event_type varchar(50),
  event_data jsonb,
  deleted_at timestamptz,
  deleted_by varchar(20)
);
CREATE INDEX IF NOT EXISTS clan_chat_messages_clan_ts_idx ON clan_chat_messages (clan_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS clan_chat_messages_clan_alive_idx ON clan_chat_messages (clan_id, deleted_at);

-- ---------------------------------------------------------------------------
-- clan_activities (raw-SQL table: ids from RETURNING bigint identity)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clan_activities (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  clan_id varchar(24) NOT NULL,
  activity_type varchar(50) NOT NULL,
  player_id varchar(20),
  username varchar(20),
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  timestamp timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS clan_activities_clan_ts_idx ON clan_activities (clan_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS clan_activities_clan_type_idx ON clan_activities (clan_id, activity_type);

-- ---------------------------------------------------------------------------
-- clan_alliances (raw-SQL table: ids from RETURNING bigint identity)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clan_alliances (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  clan_ids jsonb NOT NULL,
  type varchar(20) NOT NULL,
  status varchar(20) NOT NULL,
  proposed_by varchar(24) NOT NULL,
  proposed_at timestamptz NOT NULL,
  accepted_at timestamptz,
  contracts jsonb NOT NULL DEFAULT '[]'::jsonb,
  cost jsonb,
  metadata jsonb,
  broken_at timestamptz,
  broken_by varchar(20),
  cooldown_until timestamptz
);
CREATE INDEX IF NOT EXISTS clan_alliances_status_idx ON clan_alliances (status);

-- ---------------------------------------------------------------------------
-- activity_logs (secondary audit mirror written by clanActivityService)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS activity_logs (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  player_id varchar(20),
  username varchar(20),
  activity_type varchar(80) NOT NULL,
  metadata jsonb,
  timestamp timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS activity_logs_player_ts_idx ON activity_logs (player_id, timestamp DESC);

-- ---------------------------------------------------------------------------
-- beer_base_config (config singleton consumed by getBeerBaseConfig)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS beer_base_config (
  type varchar(30) PRIMARY KEY,
  config jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by varchar(20)
);

-- ---------------------------------------------------------------------------
-- game_config.type UNIQUE (race-safe upsert target; migration 0009 created the
-- drizzle-side index declaration but this constraint was never applied live)
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE tablename = 'game_config' AND indexname = 'game_config_type_unique'
  ) THEN
    CREATE UNIQUE INDEX game_config_type_unique ON game_config (type);
  END IF;
END $$;
