-- Migration 0013: clan_invitations backing table (FID-20260904-005 Phase 4)
--
-- lib/clanService.ts invitePlayerToClan (:442) writes and joinClan (:466)
-- reads clan_invitations via raw SQL, but the table never existed — the entire
-- invite→join clan lifecycle silently failed. Columns derived EXACTLY from the
-- INSERT/SELECT/UPDATE statements (invitation id is generated by the caller
-- as uuidv4-slice(24), so a 24-char varchar PK matches).

CREATE TABLE IF NOT EXISTS clan_invitations (
  id varchar(24) PRIMARY KEY,
  clan_id varchar(24) NOT NULL,
  clan_name varchar(30) NOT NULL,
  inviter_id varchar(20) NOT NULL,
  inviter_username varchar(20) NOT NULL,
  invitee_id varchar(20) NOT NULL,
  invitee_username varchar(20) NOT NULL,
  created_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'pending',
  accepted_at timestamptz
);

CREATE INDEX IF NOT EXISTS clan_invitations_invitee_status_idx
  ON clan_invitations (invitee_id, status);
CREATE INDEX IF NOT EXISTS clan_invitations_clan_idx
  ON clan_invitations (clan_id);
