ALTER TABLE player_units ADD COLUMN IF NOT EXISTS produced_at_x INTEGER;
ALTER TABLE player_units ADD COLUMN IF NOT EXISTS produced_at_y INTEGER;
ALTER TABLE player_units ADD COLUMN IF NOT EXISTS produced_date TIMESTAMPTZ;
ALTER TABLE player_units ADD COLUMN IF NOT EXISTS strength INTEGER DEFAULT 0;
ALTER TABLE player_units ADD COLUMN IF NOT EXISTS defense INTEGER DEFAULT 0;
